# Generated by Django 3.1.7 on 2021-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('_id', models.IntegerField(unique=True)),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('comercial_value', models.FloatField()),
                ('dialy_alquiler_value', models.FloatField()),
                ('allow', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
