# Generated by Django 3.1.7 on 2021-04-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('model', models.IntegerField()),
                ('comercialValue', models.IntegerField()),
                ('dialyValue', models.IntegerField()),
                ('allow', models.BooleanField()),
            ],
        ),
    ]
