# Generated by Django 3.1.7 on 2021-03-23 05:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
